### ISSUE TITLE
Uploading curation from tsv

### ISSUE THREAD

**Issue by JavierLuna** [JavierLuna/pycaprio#1]
This is a clone from https://github.com/Savanamed/pycaprio/issues/37

**Comment by JavierLuna** [comment]
@ofersabo @FrogFeather mentioning both of you to keep you posted on the issue.

It is a bit strange, as from pycaprio's side everything is uploaded the same way a document is.
I've reproduced it with both `document` and `annotation` creation with TSVs in a local setup, but I do find weird is that the document is uploaded using both `Swagger` and `pycaprio` and I can show the content with no problem.

I'll write an issue in INCEpTION to get some help from them

**Comment by JavierLuna** [comment]
Opened an issue here https://github.com/inception-project/inception/issues/2119

**Comment by reckart** [comment]
I have tried reproducing https://github.com/Savanamed/pycaprio/issues/37 but without success.

I have tried reproducing this by exporting a document as WebAnno TSV 3.2 from (format identifier `ctsv3`) from the curation page and then using the Swagger API again to upload the curation document (again using format identifier `ctsv3`). It worked for me.

**Comment by JavierLuna** [comment]
Hi @reckart, thank you for the input.

It seems like the people affected (and me, causally) were downloading a `ctsv3` document and uploading it again as a `tsv` file. It seems https://github.com/JavierLuna/pycaprio/pull/3 fixes using the deprecated format, which I assume all users where using wrongfully.

Thank you for the help and for the contribution
