### ISSUE TITLE
How to upload a description to project?

### ISSUE THREAD

**Issue by silkinresearch** [JavierLuna/pycaprio#10]
Hello, I am trying to add a description to project with creation. Is is possible?

I am creating a project this way:

```
from pycaprio import Pycaprio
client = Pycaprio(inception_host, authentication)

new_project = client.api.create_project(
    project_name = "My_test_project", 
    creator_name = "My_name"
)
```

What should I do next to make a description of project?

![image](https://user-images.githubusercontent.com/94602743/186132790-49acbde5-74bb-4b5c-b6ee-d21757a4a10f.png)

**Comment by reckart** [comment]
The project description cannot be set through the API.

What you can do is this:

* create an empty project and export it from INCEpTION
* at the root of the export ZIP file, you file a JSON file that contains all the project settings - the description can be set in there as well
* set the description there
* import the ZIP back into INCEpTION

**Comment by silkinresearch** [comment]
Thank you for the answer!
