### ISSUE TITLE
Retryable client sending empty payload on retries

### ISSUE THREAD

**Issue by JavierLuna** [JavierLuna/pycaprio#5]
It seems like the `RetryableClient` doesn't send a payload/sends an empty one when retrying a request.
Context: https://github.com/inception-project/inception/issues/2119#issuecomment-822020969

That is causing misleading exceptions/error messages and trouble when debugging INCEpTION <-> Pycaprio problems, as errors in the Swagger API are different than the ones `pycaprio` shows.

**Comment by JavierLuna** [comment]
I think I have time this weekend to tackle this. Will work a bit more on the client itself too

**Comment by JavierLuna** [comment]
So it seems scoped to only when sending files.
Pycaprio accepts IO streams, and when the request is first issued the stream has already been read, hence the empty payload.

I'll publish the fix in a separate branch, I still need to test it against the server and try to reproduce it.

I've also refactored quite a bit the http client used and should not retry such server responses.

**Comment by reckart** [comment]
What was the motivation for the retries at all? Normally such things should only be necessary if there is a flakey internet connection.

**Comment by JavierLuna** [comment]
As you pointed out, the main reason is network errors which are not so rare in cloud setups.
In addition to flaky internet connection (or rather your provider dropping packets from time to time), companies usually have their users connect to their intranets using VPNs which can bottleneck connectivity during the day in peaks.

Another reason could be that the server can be behind a proxy/reverse proxy of some sort that may add another layer of faultiness.

Other reason that I can think of is periods of operations, like upgrading to a newer version, or scaling up/down the inception instance. Not sure how the setup works now, but back in the day we had issues with connecting different inception instances to the same MySQL database, so we were kind of limited to just one. And because we used the API heavily and process stuff in batches, it was somewhat normal to overwhelm the API during some small periods of time.


Those errors usually happen in peaks and disappear naturally (I think the correct term is "transient error" but idk). That's why most http clients/SDKs have some sort of retry + exponential backoff + jitter.

Of course, the client should only retry http errors that can be consider safe to retry, and that's where my past self may have included some that now I wouldn't include 😉 

Another thing that I want to do different is to let users configure the number of retries more easily 👍

**Comment by reckart** [comment]
Would you say having a no-retry strategy by default (0 retries) and allowing a user to increase the number in a difficult environment (as you outlined) would be reasonable?

**Comment by JavierLuna** [comment]
I would be hesitant to change the default as 1) retries makes the clients more robust and 2) changing the default to no retries would be backwards compatible with the systems that already expect it to be there.

I'd want to better understand your concerns about the retries though. As I've read the issues they are causing are 1) not sending file content and 2) retrying status codes that it shouldn't have. Both will be taken care of in this issue, as the bug itself is the combination of the two.

Is there any reason beside those that goes against having retries?

**Comment by reckart** [comment]
I think in a default scenario, a retry should not be necessary. 

Depending on the type of problem, there might be other ways to get things working, e.g. switching from a synchronous requests to asynchronous requests. If a request fails, it could be that the request was actually performed but the response did not get through - or it could be that the request was performed partially. Instead of simply retrying the request, it may be necessary to check that in a failure handler and perform a clean-up action before retrying.

That is why I think retrying should be off be default and should only be turned on by people that are willing to take the risks involved.

I think that I only ever needed request retrying very rarely, e.g. while I was running a release of a large piece of software over the flakey internet connection of a high-speed train. It was only a simple CRUD repository that I pushed to, so not much risk in turning on retries. With INCEpTION, while retries when uploading and downloading annotation should be ok, it might be more of a gamble when performing complex operations such as a full project import or export.

**Comment by JavierLuna** [comment]
> I think in a default scenario, a retry should not be necessary.

You are totally right. If there are no issues, the request isn't retried. A request is only retried when the response's status code indicates that there might be an error that can be solved if retried, and I think the currently implemented solution is not great as it also retried `500s`. My proposed solution doesn't retry those, just errors related to the request being proxied, or the request being throttled.


> If a request fails, it could be that the request was actually performed but the response did not get through - or it could be that the request was performed partially. Instead of simply retrying the request, it may be necessary to check that in a failure handler and perform a clean-up action before retrying.

IMO that's a different issue that has to do with API operations [being idempotent or not](https://stripe.com/blog/idempotency). AFAIK INCEpTION's API doesn't implement any kind of idempotency mechanism, so only "safe" HTTP verbs are idempotent.

I'd be happy to work with you in implementing idempotent operations in both the server and the client, but I'm afraid the change isn't quite straightforward and it requires some designing upfront 👍

However, if you do decide that API idempotency is not something you see worth implementing, I can deactivate retries for non-idempotent endpoints.

> With INCEpTION, while retries when uploading and downloading annotation should be ok, it might be more of a gamble when performing complex operations such as a full project import or export.

You are right, we had a lot of issues with those endpoints as well, to the extend we actually did the import ourselves in the disk and in the database directly. I do think this is a great place to implement an async operation too 👍 .

To add to this last two points, there are some places where the client can try to add idempotency/retry safety but not this last "import project" one.


Let me know what is your opinion on if making the API operations idempotent is something you want to pursue for INCEpTION. I can say that it can be really really helpful for API usage, but not sure how much bandwidth you want to allocate to that use case.

I will disable retries for non-idempotent endpoints in the meantime.
